include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/shared_widgets/phone_input_widget/**.dart
    - lib/shared_widgets/phone_input_widget/src/**/**.dart
    - lib/shared_widgets/phone_input_widget/src/**/**/**.dart

linter:
  rules:
    avoid_classes_with_only_static_members: false
    always_specify_types: false
    avoid_function_literals_in_foreach_calls: false
    prefer_if_elements_to_conditional_expressions: false
    prefer_function_declarations_over_variables: false
    use_setters_to_change_properties: false