name: copy_trading
description: A Copy trading center

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  carousel_slider: ^3.0.0
  device_info: ^2.0.0
  fl_chart: ^0.12.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.13.1+1
  flutter_svg: ^0.19.3
  flutter_webview_plugin: ^0.3.11
  get_it: ^6.0.0
  grouped_list: ^3.7.1
  http: ^0.13.1
  image_picker: ^0.7.3
  intl: ^0.17.0
  intl_phone_number_input: ^0.6.0
  local_auth: ^1.1.0
  lottie: ^1.0.1
  package_info: ^2.0.0
  pin_code_text_field: ^1.7.1
  shared_preferences: ^2.0.5
  wifi: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900

